#ifndef CONDITION4DIRMONITORALL_GLOBAL_H
#define CONDITION4DIRMONITORALL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CONDITION4DIRMONITORALL_EXPORTS
# define CONDITION4DIRMONITORALL_IMPEXP Q_DECL_EXPORT
#else
# define CONDITION4DIRMONITORALL_IMPEXP Q_DECL_IMPORT
#endif

#endif