#ifndef INTERFACESINGLE4SLAVE_GLOBAL_H
#define INTERFACESINGLE4SLAVE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef INTERFACESINGLE4SLAVE_EXPORTS
# define INTERFACESINGLE4SLAVE_IMPEXP Q_DECL_EXPORT
#else
# define INTERFACESINGLE4SLAVE_IMPEXP Q_DECL_IMPORT
#endif

#endif