#ifndef INTERFACESINGLE4MASTER_GLOBAL_H
#define INTERFACESINGLE4MASTER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef INTERFACESINGLE4MASTER_EXPORTS
# define INTERFACESINGLE4MASTER_IMPEXP Q_DECL_EXPORT
#else
# define INTERFACESINGLE4MASTER_IMPEXP Q_DECL_IMPORT
#endif

#endif //CONDITIONTRIGGER_GLOBAL_H