#ifndef CONDITION4DIRMONITOR_GLOBAL_H
#define CONDITION4DIRMONITOR_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CONDITION4DIRMONITOR_EXPORTS
# define CONDITION4DIRMONITOR_IMPEXP Q_DECL_EXPORT
#else
# define CONDITION4DIRMONITOR_IMPEXP Q_DECL_IMPORT
#endif

#endif