######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 20 16:21:06 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += common_global.h \
           global_def.hpp \
           Task.hpp
SOURCES += Task.cpp test.cpp Serialization.cpp
