#ifndef CONDITION4TIMER_GLOBAL_H
#define CONDITION4TIMER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CONDITION4TIMER_EXPORTS
# define CONDITION4TIMER_IMPEXP Q_DECL_EXPORT
#else
# define CONDITION4TIMER_IMPEXP Q_DECL_IMPORT
#endif

#endif