# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/disk/PTPS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/disk/PTPS

# Include any dependencies generated for this target.
include SQLITE_wrapper/CMakeFiles/SQLITE_wrapper.dir/depend.make

# Include the progress variables for this target.
include SQLITE_wrapper/CMakeFiles/SQLITE_wrapper.dir/progress.make

# Include the compile flags for this target's objects.
include SQLITE_wrapper/CMakeFiles/SQLITE_wrapper.dir/flags.make

SQLITE_wrapper/CMakeFiles/SQLITE_wrapper.dir/SQLITE_wrapper.cpp.o: SQLITE_wrapper/CMakeFiles/SQLITE_wrapper.dir/flags.make
SQLITE_wrapper/CMakeFiles/SQLITE_wrapper.dir/SQLITE_wrapper.cpp.o: SQLITE_wrapper/SQLITE_wrapper.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /mnt/disk/PTPS/CMakeFiles $(CMAKE_PROGRESS_1)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object SQLITE_wrapper/CMakeFiles/SQLITE_wrapper.dir/SQLITE_wrapper.cpp.o"
	cd /mnt/disk/PTPS/SQLITE_wrapper && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/SQLITE_wrapper.dir/SQLITE_wrapper.cpp.o -c /mnt/disk/PTPS/SQLITE_wrapper/SQLITE_wrapper.cpp

SQLITE_wrapper/CMakeFiles/SQLITE_wrapper.dir/SQLITE_wrapper.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/SQLITE_wrapper.dir/SQLITE_wrapper.cpp.i"
	cd /mnt/disk/PTPS/SQLITE_wrapper && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /mnt/disk/PTPS/SQLITE_wrapper/SQLITE_wrapper.cpp > CMakeFiles/SQLITE_wrapper.dir/SQLITE_wrapper.cpp.i

SQLITE_wrapper/CMakeFiles/SQLITE_wrapper.dir/SQLITE_wrapper.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/SQLITE_wrapper.dir/SQLITE_wrapper.cpp.s"
	cd /mnt/disk/PTPS/SQLITE_wrapper && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /mnt/disk/PTPS/SQLITE_wrapper/SQLITE_wrapper.cpp -o CMakeFiles/SQLITE_wrapper.dir/SQLITE_wrapper.cpp.s

SQLITE_wrapper/CMakeFiles/SQLITE_wrapper.dir/SQLITE_wrapper.cpp.o.requires:
.PHONY : SQLITE_wrapper/CMakeFiles/SQLITE_wrapper.dir/SQLITE_wrapper.cpp.o.requires

SQLITE_wrapper/CMakeFiles/SQLITE_wrapper.dir/SQLITE_wrapper.cpp.o.provides: SQLITE_wrapper/CMakeFiles/SQLITE_wrapper.dir/SQLITE_wrapper.cpp.o.requires
	$(MAKE) -f SQLITE_wrapper/CMakeFiles/SQLITE_wrapper.dir/build.make SQLITE_wrapper/CMakeFiles/SQLITE_wrapper.dir/SQLITE_wrapper.cpp.o.provides.build
.PHONY : SQLITE_wrapper/CMakeFiles/SQLITE_wrapper.dir/SQLITE_wrapper.cpp.o.provides

SQLITE_wrapper/CMakeFiles/SQLITE_wrapper.dir/SQLITE_wrapper.cpp.o.provides.build: SQLITE_wrapper/CMakeFiles/SQLITE_wrapper.dir/SQLITE_wrapper.cpp.o

# Object files for target SQLITE_wrapper
SQLITE_wrapper_OBJECTS = \
"CMakeFiles/SQLITE_wrapper.dir/SQLITE_wrapper.cpp.o"

# External object files for target SQLITE_wrapper
SQLITE_wrapper_EXTERNAL_OBJECTS =

bin/libSQLITE_wrapper.so: SQLITE_wrapper/CMakeFiles/SQLITE_wrapper.dir/SQLITE_wrapper.cpp.o
bin/libSQLITE_wrapper.so: SQLITE_wrapper/CMakeFiles/SQLITE_wrapper.dir/build.make
bin/libSQLITE_wrapper.so: bin/libcommon.so
bin/libSQLITE_wrapper.so: /mnt/disk/soft/qt-4.8.2/lib/libQtGui.so
bin/libSQLITE_wrapper.so: /mnt/disk/soft/qt-4.8.2/lib/libQtXml.so
bin/libSQLITE_wrapper.so: /mnt/disk/soft/qt-4.8.2/lib/libQtNetwork.so
bin/libSQLITE_wrapper.so: /mnt/disk/soft/qt-4.8.2/lib/libQtCore.so
bin/libSQLITE_wrapper.so: SQLITE_wrapper/CMakeFiles/SQLITE_wrapper.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --red --bold "Linking CXX shared library ../bin/libSQLITE_wrapper.so"
	cd /mnt/disk/PTPS/SQLITE_wrapper && $(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/SQLITE_wrapper.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
SQLITE_wrapper/CMakeFiles/SQLITE_wrapper.dir/build: bin/libSQLITE_wrapper.so
.PHONY : SQLITE_wrapper/CMakeFiles/SQLITE_wrapper.dir/build

SQLITE_wrapper/CMakeFiles/SQLITE_wrapper.dir/requires: SQLITE_wrapper/CMakeFiles/SQLITE_wrapper.dir/SQLITE_wrapper.cpp.o.requires
.PHONY : SQLITE_wrapper/CMakeFiles/SQLITE_wrapper.dir/requires

SQLITE_wrapper/CMakeFiles/SQLITE_wrapper.dir/clean:
	cd /mnt/disk/PTPS/SQLITE_wrapper && $(CMAKE_COMMAND) -P CMakeFiles/SQLITE_wrapper.dir/cmake_clean.cmake
.PHONY : SQLITE_wrapper/CMakeFiles/SQLITE_wrapper.dir/clean

SQLITE_wrapper/CMakeFiles/SQLITE_wrapper.dir/depend:
	cd /mnt/disk/PTPS && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /mnt/disk/PTPS /mnt/disk/PTPS/SQLITE_wrapper /mnt/disk/PTPS /mnt/disk/PTPS/SQLITE_wrapper /mnt/disk/PTPS/SQLITE_wrapper/CMakeFiles/SQLITE_wrapper.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : SQLITE_wrapper/CMakeFiles/SQLITE_wrapper.dir/depend

