#ifndef CONDITIONTRIGGER_GLOBAL_H
#define CONDITIONTRIGGER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CONDITIONTRIGGER_EXPORTS
# define CONDITIONTRIGGER_IMPEXP Q_DECL_EXPORT
#else
# define CONDITIONTRIGGER_IMPEXP Q_DECL_IMPORT
#endif

#endif //CONDITIONTRIGGER_GLOBAL_H