#ifndef CONDITION4CYCLETIMER_GLOBAL_H
#define CONDITION4CYCLETIMER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CONDITION4CYCLETIMER_EXPORTS
# define CONDITION4CYCLETIMER_IMPEXP Q_DECL_EXPORT
#else
# define CONDITION4CYCLETIMER_IMPEXP Q_DECL_IMPORT
#endif

#endif