#ifndef TASKCONTROLLER_GLOBAL_H
#define TASKCONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef TASKCONTROLLER_EXPORTS
# define TASKCONTROLLER_IMPEXP Q_DECL_EXPORT
#else
# define TASKCONTROLLER_IMPEXP Q_DECL_IMPORT
#endif

#endif //PTPSAPP_GLOBAL_H