#ifndef JOBDISPATCHER_GLOBAL_H
#define JOBDISPATCHER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef JOBDISPATCHER_EXPORTS
# define JOBDISPATCHER_IMPEXP Q_DECL_EXPORT
#else
# define JOBDISPATCHER_IMPEXP Q_DECL_IMPORT
#endif

#endif //PTPSAPP_GLOBAL_H